version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    platform: linux/amd64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    build: .  # <--- WAJIB: Agar Docker menjalankan Dockerfile & install pandas
    container_name: airflow_webserver
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # Kunci rahasia untuk hilangkan error 403 Forbidden
      - AIRFLOW__WEBSERVER__SECRET_KEY=super_secret_lion_parcel_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
      airflow webserver"

  airflow-scheduler:
    build: . # <--- WAJIB: Sama dengan webserver
    container_name: airflow_scheduler
    platform: linux/amd64
    depends_on:
      airflow-webserver:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=super_secret_lion_parcel_123 # <--- Harus sama
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: scheduler